# Generated by Django 3.2.15 on 2022-10-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_board_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалена'),
        ),
    ]
