# Generated by Django 3.2.15 on 2022-11-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(verbose_name='ID чата')),
                ('username', models.CharField(max_length=50, null=True, verbose_name='Username пользователя в tg')),
                ('verification_code', models.CharField(max_length=150, verbose_name='Код верификации')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
            },
        ),
    ]
